apiVersion: apps/v1
kind: Deployment
metadata:
  name: exerciselog-api-deployment
  labels:
    app: exerciselog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exerciselog-api
  template:
    metadata:
      labels:
        app: exerciselog-api
    spec:
      initContainers:
      - name: exerciselog-api-migrate
        image: ghcr.io/pettermk/exerciselog-api:main-migrate
        command:
          ["dotnet", "ef", "database", "update"]
        imagePullPolicy: Always
        env:
        - name: PG_HOST
          valueFrom:
            secretKeyRef:
              name: exerciselog-db-app
              key: host
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: exerciselog-db-app
              key: user
        - name: PG_DATABASE
          valueFrom:
            secretKeyRef:
              name: exerciselog-db-app
              key: dbname
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: exerciselog-db-app
              key: password

      containers:
      - name: exerciselog-api
        image: ghcr.io/pettermk/exerciselog-api:main
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
        - name: PG_HOST
          valueFrom:
            secretKeyRef:
              name: exerciselog-db-app
              key: host
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: exerciselog-db-app
              key: user
        - name: PG_DATABASE
          valueFrom:
            secretKeyRef:
              name: exerciselog-db-app
              key: dbname
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: exerciselog-db-app
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: exerciselog-api-service
spec:
  selector:
    app: exerciselog-api
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  type: ClusterIP
