apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: exerciselog-db
spec:
  instances: 2

  bootstrap:
    initdb:
      database: exerciselog
      owner: exerciselog

  storage:
    size: 3Gi
